# Generated by Django 3.2 on 2021-09-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
