# Generated by Django 3.2 on 2021-10-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
