# Generated by Django 3.2 on 2021-10-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
