# Generated by Django 3.2 on 2021-10-15 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_auto_20211010_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
